### PR TITLE
Add sti scripts to nodejs template

### PR DESCRIPTION
**Pull request by humaton**
Add sti scripts to nodejs template

### CODE REVIEW

**Comment by humaton** [comment]
sti build passes when LABEL io.openshift.sti.scripts-url=image:///usr/share/sti/bin is set in dockerfile

**Comment by hhorak** [comment]
@mfojtik, isn't the LABEL `io.openshift.sti.scripts-url` the new implementation of what `STI_SCRIPTS_URL` did before we had LABELs then?

**Comment by mfojtik** [comment]
correct

**Comment by humaton** [comment]
Is there something that I need to do with node template? Or STI_SCRIPTS_URL will be defined per os template?

**Comment by hhorak** [comment]
@humaton wrote:

> Is there something that I need to do with node template? Or STI_SCRIPTS_URL will be defined per os template?

I think we can set something like `sti = true` in the `rhscl.yaml` for all images that ship sti scripts and implement whatever is needed in the template. That makes sure it is done the same for all images. Anyway, having `STI_SCRIPTS_URL` variable still defined in the image may be handy so the sti scripts will just use that value and not hard-code the path. Change is then done on one place only.

**Comment by hhorak** [comment]
The generic way to add LABEL is tracked here: https://github.com/sclorg/rhscl2dockerfile/issues/31

Any more issues or can we merge this PR now?

**Comment by hhorak** [comment]
@jhadvig ^ ?

**Comment by hhorak** [comment]
Sorry, this repos was made deprecated. If the issue is still in place in some of the container under https://github.com/sclorg?q=-container, then, please, report an issue for the specific container image.

**Pull request closed without merging**
