### PR TITLE
Unify RHSCL MongoDB with OpenShift #21

### PR DESCRIPTION
**Pull request by omron93**
Changes in RHSCL MongoDB images - see issue #21

### CODE REVIEW

**Comment by omron93** [comment]
@mfojtik openshift/mongodb#32 - so only MONGODB_ADMIN_PASSWORD is mandatory?

What about `if [ ! -f /var/lib/mongodb/data/.mongodb_users_created ]`.... You run container with only admin password and stop it.  Then you mount this database to starting container. You won't be able to create user during container initialization, right?

**Comment by hhorak** [comment]
@omron93 I think it is fine, because in that case you already have the data stack initialized. Creating users by specifying environment variables is valid just for first-time database initialization. If you create the container with admin password only and then pass the same data dir into another container, then you must use another way to create user/pass/db.. It makes sense to me..

**Comment by omron93** [comment]
@hhorak @mfojtik 

> I think it is fine, because in that case you already have the data stack initialized. Creating users by specifying environment variables is valid just for first-time database initialization. If you create the container with admin password only and then pass the same data dir into another container, then you must use another way to create user/pass/db.. It makes sense to me..

IMPOV this could be confusing for users:
a) they have to specify environmental variable even though any user is screated
b) they won't be able to use these specified users (won't be able to connect database), but no warning/message is printed about this!
So for me it could be better not to force them to specify USER+PASS+DB+ADMIN_PASS if users are already created. Or at least print some message about it... ??

**Comment by mfojtik** [comment]
@omron93 if users are created that means that you mounting a VOLUME with database files. In that case we should touch '.users_created' file or something with similar name to skip the user creation.

**Comment by hhorak** [comment]
@omron93 I'm not sure if I understand, so just trying just to rephrase -- I run `docker run -e ADMIN_PASS=secret -v /mydata:/var/lib/mongodb/data mongodbXX`. Then I stop the container and run `docker run -v /mydata:/var/lib/mongodb/data mongodbXX` -- now I'm not able to create any other users?

**Comment by omron93** [comment]
@hhorak Now it works in the same way as the openshift mongodb.
(@mfojtik There is an example to be clear what I wanted to mention)

1) You run `docker run -e ADMIN_PASS=secret -e _USER=usr -e _PASS=pass -e _DB=test -v /mydata:/var/lib/mongodb/data mongodbXX` (you have to specify all there env variables) -> admin user and user "usr" is created in database and file `/var/lib/mongodb/data/.mongodb_users_created` is created
2) Then you run `docker run -e ADMIN_PASS=secret2 -e _USER=usr2 -e _PASS=pass2 -e _DB=test2 -v /mydata:/var/lib/mongodb/data mongodbXX`. Because `.mongodb_users_created` file is created, user creation is skipped but user is not (at least) notified about it! (And user still have to pass all these env variables)
Database starts normally with authentication,... But when user try to connect to this database with `mongo -u admin -p secret2` or `mongo -u usr2 -p pass2` it fails.

And you are able to create other users, but you have to connect with passwords from 1) or manually start `mongod --dbpath /var/lib/mongodb/data` without auth and create users (maybe delete old ones).

**Comment by mfojtik** [comment]
@omron93 you still have to pass the _USER/_PASSWORD because when you link container the application has to know how to authenticate. That variables are also used in OpenShift and they are mandatory, because the Pods consuming this Service needs to know how to authenticate against database. Also valid case for Atomic.

**Comment by jhadvig** [comment]
> Database starts normally with authentication,... But when user try to connect to this database with mongo -u admin -p secret2 or mongo -u usr2 -p pass2 it fails.

@omron93 sure it will fail. The second run with `docker run -e ADMIN_PASS=secret2 -e _USER=usr2 -e _PASS=pass2 -e _DB=test2 -v /mydata:/var/lib/mongodb/data mongodbX` wont create the user `usr2`. Only the first run will user `usr1` + `admin`. What sense it would make to create a user everytime you will re-attache the volume with DB to the container? 
As @mfojtik mentioned every other time we are re-attaching the volume we need to provide the env vars with creds. only for the linking.

**Comment by hhorak** [comment]
It seems to me like name of the file that says whether the data stack has been initialized, was just chosen unluckily and it might have caused the misunderstanding.. Let's call it simply `.mongodb_datadir_initialized`.

Then, how I believe it should work is:
- if and only if `/var/lib/mongodb/data/.mongodb_datadir_initialized` is _not_ existing, then the `cont-mongod.sh` and `cont-mongos.sh` scripts start to parse the arguments and as soon as any initialization is done (users or admin), the file is created
- if the file _does_ exist, just the daemon is launched, nothing is initialized

Does it sound fine?

**Comment by mfojtik** [comment]
@hhorak it does! @jhadvig @mnagy, can you guys change that file name in our repos?

**Comment by jhadvig** [comment]
@mfojtik @hhorak renamed -> https://github.com/openshift/mongodb/pull/34

**Comment by omron93** [comment]
> What sense it would make to create a user everytime you will re-attache the volume with DB to the container? 

@jhadvig For example it could be possible to create another user (so to have admin user+2x user) or (if the user exists) to change his password.

But I didn't realise that this credentials have to be in container for linking...

So there shouldn't be any message about already initialized database? Or user isn't able to change value of variables between first and second start with mounted database?

`if [ ! -f $dbpath/.mongodb_datadir_initialized  ]; then    ....; else  echo "=> Database directory is already initialized. Skipping creating users..."; fi`

**Comment by mfojtik** [comment]
@omron93 https://github.com/openshift/mongodb/pulls

**Comment by omron93** [comment]
@mfojtik @jhadvig Any issues with this?

**Pull request merged**
