### PR TITLE
Create and use default user if not re-defined for the image

### PR DESCRIPTION
**Pull request by hhorak**
And also use the user IDs instead of user name because of https://github.com/openshift/sti-php/pull/13#issuecomment-103877177

### CODE REVIEW

**Comment by hhorak** [comment]
@mfojtik @bparees Does it seem fine for you?

**Comment by mfojtik** [comment]
@cswong

**Comment by soltysh** [comment]
@mfojtik I think you've meant @csrwng :wink:

**Comment by mfojtik** [comment]
@soltysh yes :-) sorry Cesar....

**Comment by csrwng** [comment]
LGTM

**Pull request merged**
