### PR TITLE
MySQL config+other PaaS features backported from openshift

### PR DESCRIPTION
**Pull request by hhorak**
@mfojtik @mnagy Hopefully this implements the whole set of features from openshift's mysql, excluding those differences:
- user/pass/db is not compulsory if admin password is given (we agreed an that, but openshift image is still requiring user/pass/db everytime)
- arbitrary UID feature is not working yet -- waiting for resolution in issue #18
- config location is on standard path -- /etc/my.cnf -- this should be transparent for user and this way may use rpm's defaults for `plugindir` etc..
- master/slave replication is not there (it's not necessary for now, as discussed few times in last days)

Are there any other differences or issues with the changes?

### CODE REVIEW

**Comment by mfojtik** [comment]
> user/pass/db is not compulsory if admin password is given (we agreed an that, but openshift image is still requiring user/pass/db everytime)

https://github.com/openshift/mongodb/issues/32

**Comment by omron93** [comment]
> Are there any other differences or issues with the changes?

@hhorak @mfojtik  What about test directory? I hope it is still valid not to include it... (same for MongoDB)

**Comment by mfojtik** [comment]
@omron93 the test dir should be excluded (not part of the image), we use it in our internal Jenkins flow at this moment.

**Comment by hhorak** [comment]
No issues then, can we merge?

**Comment by hhorak** [comment]
Well, merging, if there are some issues, we can create issue even later.

**Pull request merged**
